services:
  map-back:
    image: node:24-alpine3.21
    container_name: map-back
    ports:
      - "3000:3000"
    volumes:
      - .:/api
    working_dir: /api
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db-map
    networks:
      - map-app

  db-map:
    image: postgres:17.5-alpine3.21
    container_name: db-map
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./.database:/var/lib/postgresql/data
    networks:
      - map-app

  map-adminer:
    image: adminer:latest
    container_name: map-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db-map
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: ${DB_NAME}
    networks:
      - map-app

networks:
  map-app:
    external: true